/* テーマ＝暮らしを見るレンズ。
   翻訳してよいのはラベル・色・語彙・呼びかけだけ。
   結論・ToDo・決定事項など、AIが抽出した記録そのものの中身はどのテーマでも変えない。 */

import { backgroundPatterns } from "./backgroundPatterns.js";

export const themes = {
  techo: {
    id: "techo",
    name: "手帳",
    emoji: "📔",
    blurb: "ビジネスの記録も、静かに整えたい人へ",
    tokens: {
      paper: "#F5F1E8", card: "#FFFFFF", ink: "#201F1B", inkSoft: "#3A392F",
      inkFaint: "#5E5C4F", line: "#C9C0A8", accent: "#3F5C42", accentBg: "#E7EEE4",
      // ビジネス用途を想定し、文学的な明朝体ではなく、端正なゴシック体を見出しに使う
      headingFont: "'Noto Sans JP', 'Zen Kaku Gothic New', sans-serif",
      ...backgroundPatterns.techo,
    },
    labels: {
      welcomeTitle: "Filovitaへようこそ",
      welcomeBody: [
        "Filovitaは、暮らしの後始末を静かに引き受ける道具です。",
        "会話や出来事を記録し、必要なときだけ声をかけます。",
        "判断するのは、いつもあなたです。",
      ],
      welcomeCta: "はじめる",
      calendarHeading: "今月の暮らし",
      continuationCta: "今日の続きを見る",
      todoRemainingLabel: "残っているToDo",
      todoNoneLabel: "今のところ、残っていることはありません",
      nextLabel: "次は",
      conclusionLabel: "今回の結論",
      todoSectionLabel: "ToDo",
      addTodoCta: "＋ 思い出したことを追加",
      myNoteLabel: "所感",
      myNotePlaceholder: "そのときの気持ちや、まだ確信のない考えを、ここに",
      myNoteHint: "ここに書いたことは、決定事項やToDoにはしません。あとで「#所感」を開けば、まとめて辿れます。",
      confirmIntro: "AIが下書きを作りました。違うところだけ、教えてください。",
      confirmCta: "この内容で確定する",
      confirmedMessage: "これで終わりです、おつかれさまでした",
      backToCalendarCta: "カレンダーへ戻る",
    },
  },
  ehon: {
    id: "ehon",
    name: "絵本",
    emoji: "📖",
    blurb: "やさしい言葉で、気持ちを軽くしたい人へ",
    tokens: {
      paper: "#FBEEE0", card: "#FFFFFF", ink: "#4A2E2A", inkSoft: "#6B4A3E",
      inkFaint: "#9C7A6B", line: "#E8C9A8", accent: "#E8837A", accentBg: "#FBE3DE",
      headingFont: "'Shippori Mincho', serif",
      ...backgroundPatterns.ehon,
    },
    labels: {
      welcomeTitle: "Filovitaへ、ようこそ",
      welcomeBody: [
        "Filovitaは、くらしのあとかたづけを、そっと引き受けるお手伝いです。",
        "お話ししたことを、かわりに覚えておくよ。",
        "きめるのは、いつでも、あなた。",
      ],
      welcomeCta: "はじめてみる",
      calendarHeading: "こんげつの、くらし",
      continuationCta: "きょうのつづきをみる",
      todoRemainingLabel: "のこっている、やくそく",
      todoNoneLabel: "いまは、のこっていることはないよ",
      nextLabel: "つぎは",
      conclusionLabel: "きょうのおはなし",
      todoSectionLabel: "つぎにすること",
      addTodoCta: "＋ おもいだしたことをたす",
      myNoteLabel: "きもち",
      myNotePlaceholder: "そのときのきもちを、ここに書いてね",
      myNoteHint: "ここに書いたことは、やくそくにはしないよ。あとで「#きもち」をひらけば、まとめてみられるよ。",
      confirmIntro: "下書きができたよ。ちがうところがあったら教えてね。",
      confirmCta: "これでいいよ",
      confirmedMessage: "おわったよ、よくがんばったね",
      backToCalendarCta: "カレンダーにもどる",
    },
  },
  mori: {
    id: "mori",
    name: "森",
    emoji: "🌲",
    blurb: "自然の中にいるような、静かな安心感がほしい人へ",
    tokens: {
      paper: "#EEF2E6", card: "#FFFFFF", ink: "#1F2E1A", inkSoft: "#33452B",
      inkFaint: "#5C6E52", line: "#B9C9A8", accent: "#2F6B3A", accentBg: "#DCEBDD",
      headingFont: "'Shippori Mincho', serif",
      ...backgroundPatterns.mori,
    },
    labels: {
      welcomeTitle: "Filovitaの森へ",
      welcomeBody: [
        "Filovitaは、暮らしの後始末をそっと引き受ける、静かな道具です。",
        "出来事を記録し、必要なときだけ声をかけます。",
        "歩む道を決めるのは、いつもあなたです。",
      ],
      welcomeCta: "歩きはじめる",
      calendarHeading: "今月の木々",
      continuationCta: "今日の足あとを見る",
      todoRemainingLabel: "残っている芽",
      todoNoneLabel: "今は、芽吹きを待つものはありません",
      nextLabel: "次に見えるのは",
      conclusionLabel: "今回、根づいたこと",
      todoSectionLabel: "見守ること",
      addTodoCta: "＋ 気にかけることを増やす",
      myNoteLabel: "木漏れ日メモ",
      myNotePlaceholder: "そのときの気持ちを、ここに",
      myNoteHint: "ここに書いたことは、決定事項やToDoにはしません。あとで「#木漏れ日メモ」を開けば、まとめて辿れます。",
      confirmIntro: "下書きができました。違うところだけ、教えてください。",
      confirmCta: "この内容で根づかせる",
      confirmedMessage: "今日も、静かに一日を終えました",
      backToCalendarCta: "森の入り口へ戻る",
    },
  },
  horror: {
    id: "horror",
    name: "ホラー",
    emoji: "🦇",
    blurb: "大変な出来事も、ちょっとしたスリルに変えて楽しみたい人へ",
    // コンポーネントテーマ：色・ラベルだけでなく、専用UI部品（theme/gothic/）を使う。
    // ただし結論→ToDo→確定という順序や確認操作の構造は、他のテーマと変えない。
    componentTheme: "gothic",
    tokens: {
      paper: "#1B1520", card: "#241C2C", ink: "#EDE6F0", inkSoft: "#C9BBD1",
      inkFaint: "#8F7F99", line: "#4A3A55", accent: "#B5324A", accentBg: "#3A2230",
      headingFont: "'Shippori Mincho', serif",
      ...backgroundPatterns.horror,
    },
    labels: {
      welcomeTitle: "ようこそ、Filovita館へ",
      welcomeBody: [
        "Filovitaは、暮らしの後始末を静かに引き受ける、忠実な執事です。",
        "出来事を記録し、必要なときだけそっと囁きます。",
        "館の主はいつも、あなたです。",
      ],
      welcomeCta: "扉を開く",
      calendarHeading: "今月の記録簿",
      continuationCta: "今日の続きを覗く",
      todoRemainingLabel: "未解決の案件",
      todoNoneLabel: "今のところ、封じるべきものはありません",
      nextLabel: "次に訪れるのは",
      conclusionLabel: "今回、明らかになったこと",
      todoSectionLabel: "封印すべきこと",
      addTodoCta: "＋ 思い出した影を追加",
      myNoteLabel: "独白",
      myNotePlaceholder: "そのときの気持ちや、まだ確信のない考えを、ここに",
      myNoteHint: "ここに書いたことは、決定事項やToDoにはしません。あとで「#独白」を開けば、まとめて辿れます。",
      confirmIntro: "執事が下書きを作りました。違うところだけ、お申し付けください。",
      confirmCta: "この内容で封をする",
      confirmedMessage: "この件は、無事に鎮まりました",
      backToCalendarCta: "記録簿へ戻る",
    },
  },
  sf: {
    id: "sf",
    name: "SF",
    emoji: "🛰️",
    blurb: "淡々と、データのように整理して眺めたい人へ",
    tokens: {
      paper: "#0D1B24", card: "#132A38", ink: "#DCEFF5", inkSoft: "#A9C7D4",
      inkFaint: "#6E8A96", line: "#274456", accent: "#2FB6C4", accentBg: "#123540",
      headingFont: "'Shippori Mincho', serif",
      ...backgroundPatterns.sf,
    },
    labels: {
      welcomeTitle: "Filovita起動",
      welcomeBody: [
        "Filovitaは、生活ログを静かに処理する支援システムです。",
        "出来事を記録し、必要な時のみ通知します。",
        "最終判断権は、常にオペレーターにあります。",
      ],
      welcomeCta: "システム開始",
      calendarHeading: "今月のログ",
      continuationCta: "本日の続きを表示",
      todoRemainingLabel: "未処理タスク",
      todoNoneLabel: "現在、未処理のタスクはありません",
      nextLabel: "次回スケジュール",
      conclusionLabel: "解析結果",
      todoSectionLabel: "未処理タスク",
      addTodoCta: "＋ タスクを追加",
      myNoteLabel: "所感ログ",
      myNotePlaceholder: "感覚データや未確定の推測を、ここに記録",
      myNoteHint: "ここに記録した内容は、決定事項やタスクには昇格しません。「#所感ログ」から後で参照できます。",
      confirmIntro: "AIが解析結果を生成しました。差異があれば修正してください。",
      confirmCta: "この内容で確定する",
      confirmedMessage: "処理完了。ログを記録しました",
      backToCalendarCta: "ログ一覧へ戻る",
    },
  },
  bouken: {
    id: "bouken",
    name: "冒険",
    emoji: "🗺️",
    blurb: "今日も一つ、クエストをクリアした気分になりたい人へ",
    tokens: {
      paper: "#F2E3C6", card: "#FFF8E8", ink: "#3B2A14", inkSoft: "#5B4425",
      inkFaint: "#8A6E44", line: "#D8B978", accent: "#C97A2B", accentBg: "#F5DCB2",
      headingFont: "'Shippori Mincho', serif",
      ...backgroundPatterns.bouken,
    },
    labels: {
      welcomeTitle: "冒険の書、開始",
      welcomeBody: [
        "Filovitaは、日々の冒険の後片付けを引き受ける相棒です。",
        "出来事を記録し、必要な時だけ声をかけます。",
        "進む道を決めるのは、いつも勇者であるあなたです。",
      ],
      welcomeCta: "冒険をはじめる",
      calendarHeading: "今月の旅路",
      continuationCta: "今日の冒険を見る",
      todoRemainingLabel: "残っているクエスト",
      todoNoneLabel: "今は、残っているクエストはありません",
      nextLabel: "次のイベントは",
      conclusionLabel: "今回の成果",
      todoSectionLabel: "次のクエスト",
      addTodoCta: "＋ 思い出したクエストを追加",
      myNoteLabel: "冒険メモ",
      myNotePlaceholder: "そのときの気持ちや、まだ確信のない考えを、ここに",
      myNoteHint: "ここに書いたことは、成果やクエストにはしません。あとで「#冒険メモ」を開けば、まとめて辿れます。",
      confirmIntro: "AIが下書きを作りました。違うところだけ、教えてください。",
      confirmCta: "この内容でクエストクリア",
      confirmedMessage: "クエストクリア！おつかれさま",
      backToCalendarCta: "旅の地図へ戻る",
    },
  },
  cyberpunk: {
    id: "cyberpunk",
    name: "サイバーパンク",
    emoji: "🔩",
    blurb: "無機質な端末の向こうから、暮らしを見張りたい人へ",
    // コンポーネントテーマ：色・ラベルだけでなく、専用UI部品（theme/industrial/）を使う。
    // ただし結論→ToDo→確定という順序や確認操作の構造は、他のテーマと変えない。
    componentTheme: "industrial",
    tokens: {
      paper: "#0A0D0A", card: "#12160F", ink: "#C9FFC9", inkSoft: "#7FE07F",
      inkFaint: "#3E5A3E", line: "#2A3A26", accent: "#39FF6A", accentBg: "#123018",
      headingFont: "'Shippori Mincho', serif",
      ...backgroundPatterns.cyberpunk,
    },
    labels: {
      welcomeTitle: "端末：Filovita 起動シーケンス",
      welcomeBody: [
        "Filovitaは、生活データを処理する産業端末である。",
        "出来事を記録し、警告が必要な時のみ点灯する。",
        "最終承認権は、常にオペレーター、あなたにある。",
      ],
      welcomeCta: "起動",
      calendarHeading: "月次ログ",
      continuationCta: "本日ログを展開",
      todoRemainingLabel: "未処理案件",
      todoNoneLabel: "現在、未処理案件なし",
      nextLabel: "次回起動",
      conclusionLabel: "解析結果",
      todoSectionLabel: "未処理案件",
      addTodoCta: "＋ 案件を追加",
      myNoteLabel: "オペレーターログ",
      myNotePlaceholder: "感覚データ、未確定推測をここに記録",
      myNoteHint: "この記録は決定事項・案件には昇格しない。「#オペレーターログ」から後で参照可能。",
      confirmIntro: "端末が解析結果を生成した。差異があれば修正せよ。",
      confirmCta: "この内容で承認",
      confirmedMessage: "承認完了。ログに記録した",
      backToCalendarCta: "ログ一覧へ戻る",
    },
  },
};

export const themeList = Object.values(themes);
export const defaultThemeId = "techo";
